type = "blockheaderfeeder"
schemaVersion = 1
name = "blockheaderfeeder"
forwardingAllowed = false
coordinatorV2Address = "{{.VRF_COORDINATOR_ADDRESS}}"
waitBlocks = 260
lookbackBlocks = 500
blockhashStoreAddress = "{{.BLOCKHASH_STORE_ADDRESS}}"
batchBlockhashStoreAddress = "{{.BATCH_BLOCKHASH_STORE_ADDRESS}}"
pollPeriod = "30s"
runTimeout = "1h"
evmChainID = "{{.ChainID}}"
fromAddresses = ["{{.ETH_ADDRESS}}"]
getBlockhashesBatchSize = 50
storeBlockhashesBatchSize = 10
