type = "blockhashstore"
schemaVersion = 1
name = "blockhashstore"
forwardingAllowed = false
coordinatorV2Address = "{{.VRF_COORDINATOR_ADDRESS}}"
coordinatorV2PlusAddress = "{{.VRF_COORDINATOR_ADDRESS}}"
waitBlocks = 30
lookbackBlocks = 200
blockhashStoreAddress = "{{.BLOCKHASH_STORE_ADDRESS}}"
batchBlockhashStoreAddress = "{{.BATCH_BLOCKHASH_STORE_ADDRESS}}"
pollPeriod = "2s"
runTimeout = "1m"
evmChainID = "{{.ChainID}}"
fromAddresses = ["{{.ETH_ADDRESS}}"]