type = "offchainreporting2"
schemaVersion = 1
name = "ccip-commit-{{.SOURCE_CHAIN_SELECTOR}}-{{.DEST_CHAIN_SELECTOR}}"
maxTaskDuration = "30s"
contractID = "{{.COMMIT_STORE_ADDRESS}}"
contractConfigTrackerPollInterval = "15s"
ocrKeyBundleID = "{{.OCR2_KEY_BUNDLE}}"
transmitterID = "{{.TRANSMITTER_ADDRESS}}"
p2pv2Bootstrappers = [{{.BOOTSTRAP_PEERS}}]
relay = "evm"
pluginType = "ccip-commit"
pluginConfig = """
sourceChainSelector = {{.SOURCE_CHAIN_SELECTOR}}
destChainSelector = {{.DEST_CHAIN_SELECTOR}}
onRampAddress = "{{.ONRAMP_ADDRESS}}"
"""

[relayConfig]
chainID = {{.DEST_CHAIN_SELECTOR}} 