type = "ccip"
schemaVersion = 1
name = "ccip"
p2pV2Bootstrappers = [{{if .P2P_V2_BOOTSTRAPPER}}"{{.P2P_V2_BOOTSTRAPPER}}"{{end}}]
capabilityVersion = "v1.0.0"
capabilityLabelledName = "ccip"
p2pKeyID = "{{.P2P_KEY_ID}}"
[ocrKeyBundleIDs]
{{if .OCR2_KEY_BUNDLE }} evm = "{{.OCR2_KEY_BUNDLE}}" {{end}}

[relayConfigs]

[pluginConfig]


