type            = "webhook"
schemaVersion   = 1
name            = "{{.JOB_NAME}}"
evmChainID      = "{{.CHAIN_ID}}"
externalJobID   = "{{.EXTERNAL_JOB_ID}}"
observationSource = """
    parse   [type="jsonparse" 
            path="{{.PARSE_PATH}}" 
            data="$(jobRun.requestBody)"]

    multiply [type="multiply" 
             input="$(parse)" 
             times={{.MULTIPLY_FACTOR}}]

    encode  [type="ethabiencode" 
            abi="{{.FUNCTION_SIGNATURE}}" 
            data="{\\"0\\":$(multiply)}"]

    tx      [type="ethtx" 
            to="{{.TARGET_CONTRACT}}" 
            data="$(encode)" 
            gasLimit="{{.GAS_LIMIT}}"]

    parse -> multiply -> encode -> tx
"""
